# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xiaoling.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'xiaoling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0exiaoling.proto\x12\x08xiaoling\"\x1b\n\x0b\x43hatRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"7\n\tChatChunk\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x0f\n\rStatusRequest\"|\n\x0bStatusReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05stage\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x05 \x01(\t\x12\x10\n\x08progress\x18\x06 \x01(\x01\x12\x0f\n\x07version\x18\x07 \x01(\t\"\r\n\x0bListRequest\"\'\n\tModelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"0\n\tModelList\x12#\n\x06models\x18\x01 \x03(\x0b\x32\x13.xiaoling.ModelInfo\"\"\n\x12SwitchModelRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x1e\n\x0c\x43ommandReply\x12\x0e\n\x06output\x18\x01 \x01(\t\"E\n\nActionInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\r\n\x05\x64\x61nce\x18\x03 \x01(\x08\x12\x0c\n\x04idle\x18\x04 \x01(\x08\"3\n\nActionList\x12%\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x14.xiaoling.ActionInfo\"!\n\x11PlayActionRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x11\n\x0fShutdownRequest2\xfb\x03\n\x08XiaoLing\x12\x34\n\x04\x43hat\x12\x15.xiaoling.ChatRequest\x1a\x13.xiaoling.ChatChunk0\x01\x12;\n\tGetStatus\x12\x17.xiaoling.StatusRequest\x1a\x15.xiaoling.StatusReply\x12\x38\n\nListModels\x12\x15.xiaoling.ListRequest\x1a\x13.xiaoling.ModelList\x12\x42\n\x0bSwitchModel\x12\x1c.xiaoling.SwitchModelRequest\x1a\x15.xiaoling.StatusReply\x12\x42\n\x0e\x45xecuteCommand\x12\x18.xiaoling.CommandRequest\x1a\x16.xiaoling.CommandReply\x12:\n\x0bListActions\x12\x15.xiaoling.ListRequest\x1a\x14.xiaoling.ActionList\x12@\n\nPlayAction\x12\x1b.xiaoling.PlayActionRequest\x1a\x15.xiaoling.StatusReply\x12<\n\x08Shutdown\x12\x19.xiaoling.ShutdownRequest\x1a\x15.xiaoling.StatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xiaoling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=28
  _globals['_CHATREQUEST']._serialized_end=55
  _globals['_CHATCHUNK']._serialized_start=57
  _globals['_CHATCHUNK']._serialized_end=112
  _globals['_STATUSREQUEST']._serialized_start=114
  _globals['_STATUSREQUEST']._serialized_end=129
  _globals['_STATUSREPLY']._serialized_start=131
  _globals['_STATUSREPLY']._serialized_end=255
  _globals['_LISTREQUEST']._serialized_start=257
  _globals['_LISTREQUEST']._serialized_end=270
  _globals['_MODELINFO']._serialized_start=272
  _globals['_MODELINFO']._serialized_end=311
  _globals['_MODELLIST']._serialized_start=313
  _globals['_MODELLIST']._serialized_end=361
  _globals['_SWITCHMODELREQUEST']._serialized_start=363
  _globals['_SWITCHMODELREQUEST']._serialized_end=397
  _globals['_COMMANDREQUEST']._serialized_start=399
  _globals['_COMMANDREQUEST']._serialized_end=432
  _globals['_COMMANDREPLY']._serialized_start=434
  _globals['_COMMANDREPLY']._serialized_end=464
  _globals['_ACTIONINFO']._serialized_start=466
  _globals['_ACTIONINFO']._serialized_end=535
  _globals['_ACTIONLIST']._serialized_start=537
  _globals['_ACTIONLIST']._serialized_end=588
  _globals['_PLAYACTIONREQUEST']._serialized_start=590
  _globals['_PLAYACTIONREQUEST']._serialized_end=623
  _globals['_SHUTDOWNREQUEST']._serialized_start=625
  _globals['_SHUTDOWNREQUEST']._serialized_end=642
  _globals['_XIAOLING']._serialized_start=645
  _globals['_XIAOLING']._serialized_end=1152
# @@protoc_insertion_point(module_scope)
