# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xiaoling_pb2 as xiaoling__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xiaoling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XiaoLingStub:
    """小凌 v0.0.3：Flutter(UI) + Python(AI后端) + gRPC(通信) 混合架构
    Flutter 客户端通过 localhost:50051 与 Python 后端通信。

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/xiaoling.XiaoLing/Chat',
                request_serializer=xiaoling__pb2.ChatRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/xiaoling.XiaoLing/GetStatus',
                request_serializer=xiaoling__pb2.StatusRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/xiaoling.XiaoLing/ListModels',
                request_serializer=xiaoling__pb2.ListRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.ModelList.FromString,
                _registered_method=True)
        self.SwitchModel = channel.unary_unary(
                '/xiaoling.XiaoLing/SwitchModel',
                request_serializer=xiaoling__pb2.SwitchModelRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/xiaoling.XiaoLing/ExecuteCommand',
                request_serializer=xiaoling__pb2.CommandRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.CommandReply.FromString,
                _registered_method=True)
        self.ListActions = channel.unary_unary(
                '/xiaoling.XiaoLing/ListActions',
                request_serializer=xiaoling__pb2.ListRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.ActionList.FromString,
                _registered_method=True)
        self.PlayAction = channel.unary_unary(
                '/xiaoling.XiaoLing/PlayAction',
                request_serializer=xiaoling__pb2.PlayActionRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/xiaoling.XiaoLing/Shutdown',
                request_serializer=xiaoling__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=xiaoling__pb2.StatusReply.FromString,
                _registered_method=True)


class XiaoLingServicer:
    """小凌 v0.0.3：Flutter(UI) + Python(AI后端) + gRPC(通信) 混合架构
    Flutter 客户端通过 localhost:50051 与 Python 后端通信。

    """

    def Chat(self, request, context):
        """对话（流式返回，模拟打字机效果）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """获取当前状态（成长阶段 / 模型档位 / 渲染后端）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """列出可用models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchModel(self, request, context):
        """切换models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """执行终端指令（/帮助、/成长报告 等）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActions(self, request, context):
        """列出可用动作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayAction(self, request, context):
        """播放动作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """关闭后端
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XiaoLingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=xiaoling__pb2.ChatRequest.FromString,
                    response_serializer=xiaoling__pb2.ChatChunk.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=xiaoling__pb2.StatusRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=xiaoling__pb2.ListRequest.FromString,
                    response_serializer=xiaoling__pb2.ModelList.SerializeToString,
            ),
            'SwitchModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchModel,
                    request_deserializer=xiaoling__pb2.SwitchModelRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=xiaoling__pb2.CommandRequest.FromString,
                    response_serializer=xiaoling__pb2.CommandReply.SerializeToString,
            ),
            'ListActions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActions,
                    request_deserializer=xiaoling__pb2.ListRequest.FromString,
                    response_serializer=xiaoling__pb2.ActionList.SerializeToString,
            ),
            'PlayAction': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayAction,
                    request_deserializer=xiaoling__pb2.PlayActionRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=xiaoling__pb2.ShutdownRequest.FromString,
                    response_serializer=xiaoling__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xiaoling.XiaoLing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xiaoling.XiaoLing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XiaoLing:
    """小凌 v0.0.3：Flutter(UI) + Python(AI后端) + gRPC(通信) 混合架构
    Flutter 客户端通过 localhost:50051 与 Python 后端通信。

    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xiaoling.XiaoLing/Chat',
            xiaoling__pb2.ChatRequest.SerializeToString,
            xiaoling__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/GetStatus',
            xiaoling__pb2.StatusRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListModels',
            xiaoling__pb2.ListRequest.SerializeToString,
            xiaoling__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/SwitchModel',
            xiaoling__pb2.SwitchModelRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ExecuteCommand',
            xiaoling__pb2.CommandRequest.SerializeToString,
            xiaoling__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/ListActions',
            xiaoling__pb2.ListRequest.SerializeToString,
            xiaoling__pb2.ActionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/PlayAction',
            xiaoling__pb2.PlayActionRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoling.XiaoLing/Shutdown',
            xiaoling__pb2.ShutdownRequest.SerializeToString,
            xiaoling__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
